import difflib
import json
from importlib.metadata import version
from pathlib import Path

import pytest
import yaml
from fastapi.testclient import TestClient
from pydantic import TypeAdapter

from registry_api.main import create_app
from registry_api.openapi_metadata import (
    ADMIN_ANNOTATION_EXAMPLES,
    ADMIN_ASSET_EXAMPLES,
    ADMIN_ICON_SEARCH_EXAMPLES,
    ADMIN_ICON_UPLOAD_EXAMPLES,
    ADMIN_LIFECYCLE_EXAMPLES,
    API_TITLE,
    ISSUER_ACTION_EXAMPLES,
    ISSUER_ICON_SEARCH_EXAMPLES,
    ICON_PROPOSAL_EXAMPLES,
    REGISTER_ASSET_EXAMPLES,
)
from registry_api.schemas import (
    AdminAssetAction,
    AdminIconUploadRequest,
    AdminLifecycleAction,
    IconProposalRequest,
    IssuerIconProposalSearchRequest,
    IssuerAction,
    RegisterAssetRequest,
    PendingIconProposalSearchRequest,
    UpdateAdminAnnotationsAction,
)
from registry_api.settings import Settings

SPEC_PATH = Path("openapi.yaml")
MAX_DIFF_LINES = 40


def _assert_schema_matches_snapshot(tracked: dict, generated: dict) -> None:
    if tracked == generated:
        return

    tracked_json = json.dumps(tracked, indent=2, sort_keys=True).splitlines(
        keepends=True
    )
    generated_json = json.dumps(generated, indent=2, sort_keys=True).splitlines(
        keepends=True
    )
    diff = list(
        difflib.unified_diff(
            tracked_json,
            generated_json,
            fromfile="openapi.yaml",
            tofile="generated OpenAPI",
            n=2,
        )
    )
    shown = diff[:MAX_DIFF_LINES]
    if len(diff) > MAX_DIFF_LINES:
        shown.append(f"... diff truncated ({len(diff) - MAX_DIFF_LINES} more lines)\n")
    pytest.fail(
        "OpenAPI snapshot is stale; run `python scripts/generate_openapi.py`.\n"
        + "".join(shown),
        pytrace=False,
    )


def test_tracked_openapi_snapshot_matches_fastapi_schema() -> None:
    tracked = yaml.safe_load(SPEC_PATH.read_text())
    generated = create_app(settings=Settings(app_name=API_TITLE)).openapi()

    assert SPEC_PATH.read_text().startswith(
        "# Generated by scripts/generate_openapi.py. Do not edit manually.\n"
    )
    _assert_schema_matches_snapshot(tracked, generated)
    assert tracked["info"]["version"] == version("liquid-asset-registry")


def test_generated_openapi_preserves_stable_operation_ids_and_examples() -> None:
    schema = create_app().openapi()
    expected_operation_ids = {
        ("/health", "get"): "healthCheck",
        ("/", "get"): "getAllAssetsLegacyRoot",
        ("/", "post"): "registerAssetLegacyRoot",
        ("/index.json", "get"): "getAllAssetsLegacyIndex",
        ("/icons.json", "get"): "getIconsLegacy",
        ("/contract/validate", "post"): "validateContractLegacy",
        ("/{asset_id}", "get"): "getAssetLegacyRoot",
        ("/{asset_id}", "delete"): "deleteAssetLegacyRoot",
        ("/v2/assets", "post"): "registerAssetV2",
        ("/v2/assets", "get"): "searchAssetsV2",
        ("/v2/assets/all.json", "get"): "getAllAssetsV2Json",
        ("/v2/assets/{asset_id}", "get"): "getAssetV2",
        ("/v2/assets/{asset_id}/icon", "get"): "getCurrentAssetIconV2",
        (
            "/v2/assets/{asset_id}/icon/{icon_hash}.png",
            "get",
        ): "getAssetIconByHashV2",
        ("/v2/assets/{asset_id}/actions", "post"): "submitIssuerActionV2",
        ("/v2/assets/{asset_id}/actions/latest", "get"): "getLatestIssuerActionHashV2",
        ("/v2/assets/{asset_id}/icon-proposals", "post"): "submitIconProposalV2",
        (
            "/v2/assets/{asset_id}/icon-proposals/search",
            "post",
        ): "searchIssuerIconProposalsV2",
        ("/v2/assets/{asset_id}/migrate", "post"): "migrateLegacyAssetToV2",
        ("/v2/assets/{asset_id}/audit", "get"): "getAssetAuditLogV2",
        ("/v2/audit", "get"): "searchAuditLogV2",
        ("/v2/admin/assets/{asset_id}/annotations", "put"): "updateAdminAnnotationsV2",
        ("/v2/admin/actions", "post"): "submitAdminActionV2",
        ("/v2/admin/assets/{asset_id}/actions", "post"): "submitAdminAssetActionV2",
        ("/v2/admin/assets/{asset_id}/icon", "put"): "setAdminAssetIconV2",
        ("/v2/admin/icon-proposals/search", "post"): "searchPendingIconProposalsV2",
    }
    for (path, method), operation_id in expected_operation_ids.items():
        assert schema["paths"][path][method]["operationId"] == operation_id

    expected_examples = {
        ("/v2/assets", "post"): {"v2Contract", "legacyContract"},
        ("/v2/assets/{asset_id}/actions", "post"): {
            "replaceCategoryTags",
            "replaceTradingVenues",
            "replaceCustom",
            "setCustomField",
            "deleteCustomField",
            "deregister",
            "rotateIssuerPubkey",
        },
        ("/v2/admin/assets/{asset_id}/annotations", "put"): {"markFeatured"},
        ("/v2/admin/actions", "post"): {
            "addAdmin",
            "updateAdminPermissions",
            "updateAdminName",
            "removeAdmin",
        },
        ("/v2/admin/assets/{asset_id}/actions", "post"): {
            "forceDelist",
            "forceRelist",
            "approveIcon",
            "rejectIcon",
        },
        ("/v2/assets/{asset_id}/icon-proposals", "post"): {"proposeIcon"},
        ("/v2/assets/{asset_id}/icon-proposals/search", "post"): {"newestFirst"},
        ("/v2/admin/icon-proposals/search", "post"): {"oldestFirst"},
        ("/v2/admin/assets/{asset_id}/icon", "put"): {"setIcon"},
    }
    for (path, method), example_names in expected_examples.items():
        media_type = schema["paths"][path][method]["requestBody"]["content"][
            "application/json"
        ]
        assert set(media_type["examples"]) == example_names

    assert [tag["name"] for tag in schema["tags"]] == [
        "Health",
        "Legacy",
        "Assets",
        "Issuer Actions",
        "Audit",
        "Admin",
    ]


def test_openapi_examples_validate_against_request_models() -> None:
    example_groups = (
        (RegisterAssetRequest, REGISTER_ASSET_EXAMPLES),
        (IssuerAction, ISSUER_ACTION_EXAMPLES),
        (UpdateAdminAnnotationsAction, ADMIN_ANNOTATION_EXAMPLES),
        (AdminLifecycleAction, ADMIN_LIFECYCLE_EXAMPLES),
        (AdminAssetAction, ADMIN_ASSET_EXAMPLES),
        (IconProposalRequest, ICON_PROPOSAL_EXAMPLES),
        (IssuerIconProposalSearchRequest, ISSUER_ICON_SEARCH_EXAMPLES),
        (PendingIconProposalSearchRequest, ADMIN_ICON_SEARCH_EXAMPLES),
        (AdminIconUploadRequest, ADMIN_ICON_UPLOAD_EXAMPLES),
    )

    for model, examples in example_groups:
        adapter = TypeAdapter(model)
        for example in examples.values():
            adapter.validate_python(example["value"])


def test_legacy_contract_request_schemas_keep_declared_field_constraints_inline() -> (
    None
):
    schemas = create_app().openapi()["components"]["schemas"]

    for request_schema_name in (
        "LegacyAssetRequest",
        "LegacyContractValidationRequest",
    ):
        contract = schemas[request_schema_name]["properties"]["contract"]
        assert "$ref" not in contract
        assert contract["properties"]["issuer_pubkey"]["minLength"] == 66
        assert contract["properties"]["issuer_pubkey"]["maxLength"] == 66
        assert contract["additionalProperties"] == {
            "$ref": "#/components/schemas/LegacyExtraValue-Input"
        }


def test_fastapi_openapi_exposes_implemented_admin_and_audit_routes() -> None:
    schema = TestClient(create_app()).get("/openapi.json").json()

    for path in (
        "/v2/admin/actions",
        "/v2/admin/assets/{asset_id}/actions",
        "/v2/admin/assets/{asset_id}/annotations",
        "/v2/assets/{asset_id}/audit",
        "/v2/assets/{asset_id}/actions/latest",
        "/v2/audit",
        "/v2/assets/{asset_id}/migrate",
        "/v2/assets/{asset_id}/icon-proposals",
        "/v2/assets/{asset_id}/icon-proposals/search",
        "/v2/admin/icon-proposals/search",
        "/v2/admin/assets/{asset_id}/icon",
    ):
        assert path in schema["paths"]

    register_parameters = schema["paths"]["/v2/assets"]["post"]["parameters"]
    signature_parameter = next(
        parameter
        for parameter in register_parameters
        if parameter["name"] == "Asset-Registry-Signature"
    )
    assert signature_parameter["required"] is False

    search_parameters = {
        parameter["name"]: parameter
        for parameter in schema["paths"]["/v2/assets"]["get"]["parameters"]
    }
    for name in ("created_after", "updated_after"):
        parameter_schema = search_parameters[name]["schema"]
        options = parameter_schema.get("anyOf", [parameter_schema])
        assert any(option.get("format") == "date-time" for option in options)

    audit_parameters = {
        parameter["name"]: parameter
        for parameter in schema["paths"]["/v2/audit"]["get"]["parameters"]
    }
    assert audit_parameters["order"]["schema"]["enum"] == ["asc", "desc"]
    assert audit_parameters["order"]["schema"]["default"] == "asc"


def test_rate_limited_endpoints_document_429_responses() -> None:
    paths = create_app().openapi()["paths"]

    for path in (
        "/",
        "/v2/assets",
        "/v2/assets/{asset_id}/migrate",
    ):
        assert "429" in paths[path]["post"]["responses"]

    assert "429" not in paths["/v2/assets"]["get"]["responses"]
