import argparse
import difflib
import sys
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from registry_api.main import create_app  # noqa: E402
from registry_api.openapi_metadata import API_TITLE  # noqa: E402
from registry_api.settings import Settings  # noqa: E402


GENERATED_HEADER = "# Generated by scripts/generate_openapi.py. Do not edit manually.\n"
DEFAULT_OUTPUT = ROOT / "openapi.yaml"
MAX_DIFF_LINES = 40


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def render_openapi_yaml() -> str:
    schema = create_app(settings=Settings(app_name=API_TITLE)).openapi()
    rendered = yaml.safe_dump(
        schema,
        allow_unicode=True,
        sort_keys=False,
        width=120,
    )
    return GENERATED_HEADER + rendered


def check_snapshot(output: Path) -> int:
    expected = render_openapi_yaml()
    actual = output.read_text() if output.exists() else ""
    if actual == expected:
        print(f"OpenAPI snapshot is current: {display_path(output)}")
        return 0

    diff = list(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=display_path(output),
            tofile="generated OpenAPI",
            n=2,
        )
    )
    sys.stderr.writelines(diff[:MAX_DIFF_LINES])
    if len(diff) > MAX_DIFF_LINES:
        print(f"... diff truncated ({len(diff) - MAX_DIFF_LINES} more lines)", file=sys.stderr)
    print(
        f"OpenAPI snapshot is stale. Run: {sys.executable} scripts/generate_openapi.py",
        file=sys.stderr,
    )
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the tracked OpenAPI snapshot from FastAPI.")
    parser.add_argument("--check", action="store_true", help="Fail when the tracked snapshot is stale.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Snapshot path (default: openapi.yaml).")
    args = parser.parse_args()
    output = args.output.resolve()

    if args.check:
        return check_snapshot(output)

    output.write_text(render_openapi_yaml())
    print(f"Wrote OpenAPI snapshot: {display_path(output)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
